# Site setings
name: '@jamesxdigital'
description: 'The personal site and portfolio of James Milton, a Motion Designer and Creative Technologist'
# Sidebar about text
site_description: 'Motion Designer X Creative Technologist from the U.K ðŸ‡¬ðŸ‡§ living in Amsterdam ðŸ‡³ðŸ‡±â€‹ where you can find me exploring the intersections between design and digital technology.'
logo: '/assets/images/pages/about.jpg'
favicon: '/assets/images/favicon.ico'
baseurl:
production_url: 'https://jamesxdigital.com'
disqus:
mailchimp_url: https://jamesxdigital.us17.list-manage.com/subscribe/post?u=6f9c0b794760533d79eba9b46&amp;id=426dd63046&amp;f_id=00b94ce0f0

# SEO
title: '@jamesxdigital'
tagline: 'James Milton'
url: 'https://jamesxdigital.com'
author: jamesxdigital

social:
  name: James Milton
  links:
    - https://twitter.com/jamesxdigital
    - https://www.linkedin.com/in/jamesxdigital
    - https://github.com/jamesxdigital
    - https://instagram.com/jamesxdigital
    - https://medium.com/@jamesxdigital


# Social links
youtube: '@jamesxdigital'
github: 'jamesxdigital'
codepen:
dribbble:
medium: '@jamesxdigital'
instagram: 'jamesxdigital'
pinterest:
linkedin: 'jamesxdigital'

twitter:
  username: jamesxdigital
  creator: jamesxdigital
  card: summary

facebook:
  app_id: 267125577759369
  admins: jmltn.1

# Navigation
navigation:
  - text: HOME
    url: /
  - text: PORTFOLIO
    url: /portfolio/
  - text: CONTACT
    url: /contact/

# Required Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-loading-lazy
  - jekyll-target-blank


# Pagination
paginate: 20
paginate_path: "/portfolio/page:num/"

# Permalinks
permalink: /:title

# Other
markdown: kramdown
include: [_redirects]

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  authors:
    title: Authors Page
    output: true
  blog_tags:
    title: Tags Page
    output: true

# Defaults
defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/author/:title/"
    layout: author
- scope:
    path: ''
    type: blog_tags
  values:
    permalink: "/tag/:title/"
    layout: tag


github: [metadata]
